### ISSUE TITLE
Feature keys stripped?

### ISSUE THREAD

**Issue by moorsey** [Staja/Update-M365EndpointsInWGXML#1]
Thank you for this script!  I'm baffled as to how Watchguard's don't allow subscription to an allow list, like that one provided by MS, not sure how people are getting around this, other than using your script?  Very confused.

Can see the thread this script came from hasn't had an update in a while, so not sure if your keeping an eye on this and not expecting any support.  Just wondering if you came across any issues with feature keys when running your script on a config?  I get errors when opening WebBlocker for example, saying no feature keys available.  Opening the original config and all is fine

Anyway, just a quick test for today, more work to get my config right and working this week, might just be able to copy/paste the right bits between config files

Thanks again for this script

**Comment by Staja** [comment]
This script was made for my previous employer but I got approval to make sure it was licensed under GPL given the WatchGuard community interest but also so it could be forked if need be due to lack of maintenance. I may fork this project for my new employer, as they operate WatchGuard infrastructure too, but that's unlikely to happen in the short to medium term.

I would perform a diff between the original XML and the destination XML and see what has been manipulated. Maybe WatchGuard has changed the format and maybe my XML manipulation breaks something or perhaps they started digitally signing configurations somehow.

**Comment by moorsey** [comment]
Thank you for the reply, much appreciated.  Going to look into this further in the new year.  Thanks again for the tool
